---
- name: Make sure that the findutils package is installed (for find and xargs).
  apt:
    name: findutils
    state: present

- name: Make sure that the coreutils package is installed (for shuf).
  apt:
    name: findutils
    state: present

- name: Make sure that the libglib2.0-bin package is installed (for gsettings).
  apt:
    name: libglib2.0-bin
    state: present

- name: Make sure the wallpapers directory exists.
  ansible.builtin.file:
    path: "{{ wallpapers_dir }}"
    state: directory
    mode: '0755'

- name: Make sure the bin directory exists.
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
    mode: '0755'

- name: Create script for rotating wallpapers.
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/{{ script_name }}"
    content: |
      #!/bin/sh
      ## export DBUS_SESSION_BUS_ADDRESS environment variable
      PID=$(pgrep -t tty2 gnome-session)
      export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
      ## Pick a random wallpaper and set is as the background.
      /usr/bin/find {{ wallpapers_dir }} -type f | /usr/bin/shuf -n1 |  /usr/bin/xargs -n 1 -i /bin/sh -c 'v="{}"; /usr/bin/gsettings set org.gnome.desktop.background picture-uri "file://$v"'
    mode: 0744

- name: Call the rotate wallpaper script with cron.
  ansible.builtin.cron:
    name: "Rotate wallpaper."
    weekday: "{{ cron_weekday }}"
    hour: "{{ cron_hour }}"
    minute: "{{ cron_minute }}"
    job: "{{ bin_dir }}/{{ script_name }}"
    state: present
